-- Migration for the Figma-driven UI/UX update.
-- Use this if you already ran the older schema.sql before these UI fields existed.

do $$
begin
  create type order_priority as enum ('normal', 'rush');
exception when duplicate_object then null;
end $$;

alter type table_status add value if not exists 'billing';
alter type order_item_status add value if not exists 'out_for_serving';

alter table menu_items
  add column if not exists image_url text not null default '',
  add column if not exists kitchen_station varchar(60) not null default 'general',
  add column if not exists prep_time_minutes integer not null default 5 check (prep_time_minutes > 0);

alter table restaurant_tables
  add column if not exists cleaning_started_at timestamptz;

update restaurant_tables
set status = 'available',
    cleaning_started_at = null
where status::text = 'reserved';

update restaurant_tables
set capacity = 4;

update dining_sessions
set child_count = least(child_count, 4),
    adult_count = greatest(0, 4 - least(child_count, 4))
where adult_count + child_count > 4;

alter table restaurant_tables
  alter column capacity set default 4;

do $$
begin
  alter table restaurant_tables
    add constraint restaurant_tables_capacity_is_four check (capacity = 4);
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table dining_sessions
    add constraint dining_sessions_max_four_guests check (adult_count + child_count <= 4);
exception when duplicate_object then null;
end $$;

alter table dining_sessions
  add column if not exists bill_requested_at timestamptz;

alter table order_items
  add column if not exists special_instructions text not null default '',
  add column if not exists priority_level order_priority not null default 'normal',
  add column if not exists priority_reason text not null default '',
  add column if not exists expedited_at timestamptz,
  add column if not exists out_for_serving_at timestamptz;

create unique index if not exists uq_open_session_per_table
  on dining_sessions(table_id)
  where status = 'open';

create index if not exists idx_tables_active_status
  on restaurant_tables(status, table_code)
  where deleted_at is null;

create index if not exists idx_sessions_table_status_opened
  on dining_sessions(table_id, status, opened_at desc);

create index if not exists idx_sessions_status_payment_bill
  on dining_sessions(status, payment_status, bill_requested_at);

create index if not exists idx_payments_status_paid_at
  on payments(status, paid_at desc);

create index if not exists idx_orders_session_ordered
  on orders(session_id, ordered_at);

create index if not exists idx_order_items_status_requested
  on order_items(status, requested_at);

create index if not exists idx_order_items_order_status
  on order_items(order_id, status);

create index if not exists idx_order_items_priority
  on order_items(priority_level, requested_at);

create index if not exists idx_menu_items_active_category
  on menu_items(category_id, name)
  where deleted_at is null and is_available = true;

create index if not exists idx_menu_items_station
  on menu_items(kitchen_station)
  where deleted_at is null;

create index if not exists idx_inventory_items_stock
  on inventory_items(deleted_at, quantity_on_hand);

create index if not exists idx_recipes_menu_id
  on recipes(menu_id);

create index if not exists idx_recipes_ingredient_id
  on recipes(ingredient_id);

create index if not exists idx_transactions_type_occurred
  on inventory_transactions(transaction_type, occurred_at desc);

create index if not exists idx_transactions_ingredient_occurred
  on inventory_transactions(ingredient_id, occurred_at desc);

create table if not exists staff_shifts (
  shift_id bigint generated by default as identity primary key,
  user_id uuid not null references app_users(user_id),
  role_snapshot staff_role not null,
  station varchar(80) not null,
  clock_in_at timestamptz not null default now(),
  clock_out_at timestamptz,
  login_at timestamptz not null default now(),
  logout_at timestamptz,
  note text not null default '',
  check (clock_out_at is null or clock_out_at >= clock_in_at),
  check (logout_at is null or logout_at >= login_at)
);

create table if not exists staff_activity_logs (
  activity_id bigint generated by default as identity primary key,
  user_id uuid not null references app_users(user_id),
  shift_id bigint references staff_shifts(shift_id),
  action varchar(80) not null,
  entity_type varchar(40) not null,
  entity_id text not null,
  occurred_at timestamptz not null default now(),
  note text not null default ''
);

create index if not exists idx_staff_shifts_user_id on staff_shifts(user_id);
create index if not exists idx_staff_shifts_clock_in_at on staff_shifts(clock_in_at);
create unique index if not exists uq_active_shift_per_user on staff_shifts(user_id) where clock_out_at is null;
create index if not exists idx_staff_shifts_user_clock on staff_shifts(user_id, clock_in_at desc);
create index if not exists idx_staff_shifts_active on staff_shifts(user_id, clock_in_at desc) where clock_out_at is null;
create index if not exists idx_staff_activity_user_id on staff_activity_logs(user_id);
create index if not exists idx_staff_activity_shift_id on staff_activity_logs(shift_id);
create index if not exists idx_staff_activity_occurred_at on staff_activity_logs(occurred_at);
create index if not exists idx_staff_activity_occurred_desc on staff_activity_logs(occurred_at desc);

comment on column menu_items.image_url is 'Menu image path or Supabase Storage URL used by customer ordering and menu dashboards.';
comment on column menu_items.kitchen_station is 'Preparation station used to route or filter kitchen display cards.';
comment on column menu_items.prep_time_minutes is 'Target preparation time used for late-order warnings.';
comment on column restaurant_tables.cleaning_started_at is 'Timestamp used for the cashier 10-minute auto-cleaning countdown.';
comment on column order_items.special_instructions is 'Customer or cashier item-level notes shown on the kitchen display card.';
comment on column order_items.priority_level is 'Rush priority flag for red KDS cards and chef-priority reporting.';
comment on column order_items.expedited_at is 'Timestamp when staff escalated an order item.';
comment on column order_items.out_for_serving_at is 'Timestamp when a waiter picked up ready food so customer iPads can show out for serving.';
comment on column dining_sessions.bill_requested_at is 'Set when guests request a cash bill; drives the cashier payment state.';
comment on table staff_shifts is 'Clock-in/clock-out history created by the staff portal for work-hour reporting and staff accountability.';
comment on table staff_activity_logs is 'Audit trail for login, order, kitchen, payment, inventory, and manager actions.';

create or replace function send_order_item_to_table(p_order_item_id bigint, p_staff_id uuid)
returns void
language plpgsql
as $$
declare
  v_item order_items%rowtype;
  v_shift_id bigint;
begin
  select *
  into v_item
  from order_items
  where order_item_id = p_order_item_id
  for update;

  if not found then
    raise exception 'Order item % does not exist', p_order_item_id;
  end if;

  if v_item.status <> 'ready' then
    raise exception 'Order item % must be ready before it can be sent out', p_order_item_id;
  end if;

  update order_items
  set status = 'out_for_serving',
      out_for_serving_at = now()
  where order_item_id = p_order_item_id;

  select shift_id
  into v_shift_id
  from staff_shifts
  where user_id = p_staff_id
    and clock_out_at is null
  order by clock_in_at desc
  limit 1;

  insert into staff_activity_logs (
    user_id,
    shift_id,
    action,
    entity_type,
    entity_id,
    occurred_at,
    note
  )
  values (
    p_staff_id,
    v_shift_id,
    'send_to_table',
    'order_item',
    p_order_item_id::text,
    now(),
    'Waiter picked up item; customer iPad now shows out for serving'
  );
end;
$$;

comment on function send_order_item_to_table(bigint, uuid) is 'Waiter action: ready food leaves the kitchen pass and becomes visible to customers as out for serving.';

create or replace function serve_order_item(p_order_item_id bigint, p_staff_id uuid)
returns void
language plpgsql
as $$
declare
  v_item order_items%rowtype;
  v_recipe record;
  v_required numeric(12,2);
  v_shift_id bigint;
begin
  select *
  into v_item
  from order_items
  where order_item_id = p_order_item_id
  for update;

  if not found then
    raise exception 'Order item % does not exist', p_order_item_id;
  end if;

  if v_item.status <> 'out_for_serving' then
    raise exception 'Order item % must be out for serving before it can be served', p_order_item_id;
  end if;

  for v_recipe in
    select r.ingredient_id, r.quantity_used, i.quantity_on_hand, i.name, i.unit_cost
    from recipes r
    join inventory_items i on i.ingredient_id = r.ingredient_id
    where r.menu_id = v_item.menu_id
    for update of i
  loop
    v_required := v_recipe.quantity_used * v_item.quantity;

    if v_recipe.quantity_on_hand < v_required then
      raise exception 'Not enough stock for %. Required %, available %', v_recipe.name, v_required, v_recipe.quantity_on_hand;
    end if;
  end loop;

  for v_recipe in
    select r.ingredient_id, r.quantity_used, i.unit_cost
    from recipes r
    join inventory_items i on i.ingredient_id = r.ingredient_id
    where r.menu_id = v_item.menu_id
    for update of i
  loop
    v_required := v_recipe.quantity_used * v_item.quantity;

    update inventory_items
    set quantity_on_hand = quantity_on_hand - v_required
    where ingredient_id = v_recipe.ingredient_id;

    insert into inventory_transactions (
      ingredient_id,
      order_item_id,
      staff_id,
      transaction_type,
      quantity_change,
      unit_cost_snapshot,
      occurred_at,
      note
    )
    values (
      v_recipe.ingredient_id,
      p_order_item_id,
      p_staff_id,
      'usage',
      -v_required,
      v_recipe.unit_cost,
      now(),
      'Served order item'
    );
  end loop;

  update order_items
  set status = 'served',
      served_at = now()
  where order_item_id = p_order_item_id;

  select shift_id
  into v_shift_id
  from staff_shifts
  where user_id = p_staff_id
    and clock_out_at is null
  order by clock_in_at desc
  limit 1;

  insert into staff_activity_logs (
    user_id,
    shift_id,
    action,
    entity_type,
    entity_id,
    occurred_at,
    note
  )
  values (
    p_staff_id,
    v_shift_id,
    'serve_item',
    'order_item',
    p_order_item_id::text,
    now(),
    'Waiter marked item served and inventory was deducted'
  );

  update orders
  set status = 'completed'
  where order_id = v_item.order_id
    and not exists (
      select 1
      from order_items oi
      where oi.order_id = v_item.order_id
        and oi.status in ('pending', 'cooking', 'ready', 'out_for_serving')
    );
end;
$$;

comment on function serve_order_item(bigint, uuid) is 'Atomic waiter action: verify recipe stock, deduct inventory, write transactions, and mark an out-for-serving item served.';
