-- ONE-SHOT DESTRUCTIVE REBUILD FOR YUM YUM BUFFET DEMO.
-- Paste this entire file into Supabase SQL Editor to drop old project objects, recreate
-- the simplified schema, seed realistic data, and grant demo access in one run.

drop function if exists active_shift_id(uuid);
drop function if exists request_cash_bill(uuid, uuid);
drop function if exists cash_checkout_session(uuid, uuid);
drop function if exists request_bill(uuid, uuid);
drop function if exists process_cash_payment(uuid, uuid);
drop function if exists release_completed_cleaning_tables();
drop function if exists start_preparing_order_item(bigint, uuid);
drop function if exists mark_order_item_ready(bigint, uuid);
drop function if exists expedite_order_item(bigint, uuid);
drop function if exists expedite_order_item(bigint, uuid, text);
drop function if exists send_order_item_to_table(bigint, uuid);
drop function if exists serve_order_item(bigint, uuid);
drop function if exists delete_all_yum_yum_buffet_data();

drop table if exists
  inventory_transactions,
  staff_activity_logs,
  payments,
  order_items,
  orders,
  dining_sessions,
  recipes,
  menu_items,
  inventory_items,
  menu_categories,
  restaurant_tables,
  staff_shifts,
  app_users
cascade;

drop type if exists transaction_type cascade;
drop type if exists priority_level cascade;
drop type if exists order_item_status cascade;
drop type if exists order_status cascade;
drop type if exists order_source cascade;
drop type if exists payment_method cascade;
drop type if exists payment_status cascade;
drop type if exists dining_session_status cascade;
drop type if exists table_status cascade;
drop type if exists app_role cascade;

-- Yum Yum Buffet - simplified Supabase schema.
-- This file is schema-only. For a full rebuild with data, run reset-new-ux.sql.

create extension if not exists pgcrypto;

do $$ begin create type app_role as enum ('cashier', 'kitchen', 'waiter', 'manager'); exception when duplicate_object then null; end $$;
do $$ begin create type table_status as enum ('available', 'occupied', 'cleaning', 'billing'); exception when duplicate_object then null; end $$;
do $$ begin create type dining_session_status as enum ('open', 'closed'); exception when duplicate_object then null; end $$;
do $$ begin create type payment_status as enum ('unpaid', 'paid'); exception when duplicate_object then null; end $$;
do $$ begin create type payment_method as enum ('cash'); exception when duplicate_object then null; end $$;
do $$ begin create type order_status as enum ('open', 'completed', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type order_item_status as enum ('pending', 'cooking', 'ready', 'out_for_serving', 'served', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type priority_level as enum ('normal', 'rush'); exception when duplicate_object then null; end $$;
do $$ begin create type transaction_type as enum ('usage', 'manual_adjustment', 'waste', 'restock'); exception when duplicate_object then null; end $$;
alter type transaction_type add value if not exists 'waste';
alter type transaction_type add value if not exists 'restock';

create table if not exists app_users (
  user_id uuid primary key default gen_random_uuid(),
  full_name text not null,
  username text not null unique,
  password_hash text not null,
  role app_role not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

comment on table app_users is 'Staff login rows for cashier, kitchen, waiter, and manager roles. deleted_at is used for soft delete.';

create table if not exists restaurant_tables (
  table_code varchar(2) primary key,
  capacity integer not null default 4 check (capacity = 4),
  status table_status not null default 'available',
  cleaning_started_at timestamptz
);

comment on table restaurant_tables is 'Fifteen physical tables. table_code such as 01 or 15 is the identifier used by the UI.';

create table if not exists menu_categories (
  category_id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists inventory_items (
  ingredient_id bigint generated by default as identity primary key,
  name text not null,
  unit text not null,
  quantity_on_hand numeric(12,2) not null default 0 check (quantity_on_hand >= 0),
  reorder_level numeric(12,2) not null default 0 check (reorder_level >= 0),
  unit_cost numeric(12,4) not null default 0 check (unit_cost >= 0),
  deleted_at timestamptz
);

comment on table inventory_items is 'Ingredient stock master. deleted_at soft-hides ingredients while keeping history.';
comment on column inventory_items.reorder_level is 'Low-stock threshold used by the inventory and manager dashboard.';
comment on column inventory_items.unit_cost is 'Average ingredient cost per unit, used for dashboard cost calculations.';

create table if not exists menu_items (
  menu_id bigint generated by default as identity primary key,
  category_id bigint not null references menu_categories(category_id),
  name text not null,
  description text not null default '',
  image_url text not null default '',
  is_available boolean not null default true,
  deleted_at timestamptz
);

comment on table menu_items is 'Customer-facing buffet menu. Individual selling price is omitted because this is an all-you-can-eat model.';

create table if not exists recipes (
  menu_id bigint not null references menu_items(menu_id) on delete cascade,
  ingredient_id bigint not null references inventory_items(ingredient_id),
  quantity_used numeric(12,2) not null check (quantity_used > 0),
  primary key (menu_id, ingredient_id)
);

comment on table recipes is 'Recipe bridge table. One menu item can consume many ingredients and one ingredient can be used by many menu items.';

create table if not exists dining_sessions (
  session_id uuid primary key default gen_random_uuid(),
  table_code varchar(2) not null references restaurant_tables(table_code),
  cashier_id uuid references app_users(user_id),
  adult_count integer not null default 0 check (adult_count >= 0),
  child_count integer not null default 0 check (child_count >= 0),
  adult_price_snapshot numeric(10,2) not null default 399 check (adult_price_snapshot >= 0),
  child_price_snapshot numeric(10,2) not null default 259 check (child_price_snapshot >= 0),
  opened_at timestamptz not null default now(),
  bill_requested_at timestamptz,
  closed_at timestamptz,
  status dining_session_status not null default 'open',
  payment_status payment_status not null default 'unpaid',
  check (adult_count + child_count <= 4)
);

comment on table dining_sessions is 'One customer visit at one table. Price columns are snapshots so historical bills stay correct after price changes.';

create unique index if not exists uq_open_session_per_table
  on dining_sessions(table_code)
  where status = 'open';

create table if not exists orders (
  order_id bigint generated by default as identity primary key,
  session_id uuid not null references dining_sessions(session_id) on delete cascade,
  ordered_at timestamptz not null default now(),
  status order_status not null default 'open'
);

comment on table orders is 'Order header created each time the customer presses SEND ORDER.';

create table if not exists order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references orders(order_id) on delete cascade,
  menu_id bigint not null references menu_items(menu_id),
  quantity integer not null check (quantity > 0),
  status order_item_status not null default 'pending',
  special_instructions text not null default '',
  priority_level priority_level not null default 'normal',
  expedited_at timestamptz,
  requested_at timestamptz not null default now(),
  cooking_at timestamptz,
  ready_at timestamptz,
  out_for_serving_at timestamptz,
  served_at timestamptz,
  cancelled_at timestamptz
);

comment on table order_items is 'Line items sent to kitchen and waiter screens. requested_at starts the shared kitchen/waiter timer.';

create table if not exists payments (
  payment_id bigint generated by default as identity primary key,
  session_id uuid not null references dining_sessions(session_id),
  cashier_id uuid references app_users(user_id),
  method payment_method not null default 'cash',
  paid_amount numeric(10,2) not null check (paid_amount >= 0),
  paid_at timestamptz not null default now(),
  status payment_status not null default 'paid'
);

create table if not exists staff_activity_logs (
  activity_id bigint generated by default as identity primary key,
  user_id uuid references app_users(user_id),
  action text not null,
  entity_type text not null,
  entity_id text not null,
  occurred_at timestamptz not null default now()
);

comment on table staff_activity_logs is 'Simple staff audit trail for insert, update, soft delete, login, and workflow actions.';

create table if not exists inventory_transactions (
  transaction_id bigint generated by default as identity primary key,
  ingredient_id bigint not null references inventory_items(ingredient_id),
  order_item_id bigint references order_items(order_item_id),
  transaction_type transaction_type not null,
  quantity_change numeric(12,2) not null,
  unit_cost_snapshot numeric(12,4) not null default 0,
  occurred_at timestamptz not null default now()
);

comment on table inventory_transactions is 'Stock ledger. usage rows are automatic from served food; manual_adjustment rows are corrections; waste rows record lost stock; restock rows record received stock.';

create index if not exists idx_dining_sessions_table_status on dining_sessions(table_code, status, opened_at desc);
create index if not exists idx_orders_session_time on orders(session_id, ordered_at desc);
create index if not exists idx_order_items_status_time on order_items(status, requested_at);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_payments_paid_at on payments(paid_at desc);
create index if not exists idx_activity_time on staff_activity_logs(occurred_at desc);
create index if not exists idx_inventory_transactions_time on inventory_transactions(occurred_at desc, transaction_type);
create index if not exists idx_inventory_items_active_stock on inventory_items(deleted_at, quantity_on_hand);
create index if not exists idx_menu_items_active_category on menu_items(category_id) where deleted_at is null and is_available = true;

create or replace function request_bill(p_session_id uuid, p_cashier_user_id uuid)
returns void
language plpgsql
as $$
declare
  v_table_code varchar(2);
begin
  select table_code into v_table_code from dining_sessions where session_id = p_session_id and status = 'open';
  if v_table_code is null then
    raise exception 'Open dining session not found';
  end if;

  update dining_sessions set bill_requested_at = now() where session_id = p_session_id;
  update restaurant_tables set status = 'billing', cleaning_started_at = null where table_code = v_table_code;

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_cashier_user_id, 'request_bill', 'dining_session', p_session_id::text);
end;
$$;

create or replace function process_cash_payment(p_session_id uuid, p_cashier_user_id uuid)
returns numeric
language plpgsql
as $$
declare
  v_session dining_sessions%rowtype;
  v_total numeric(10,2);
begin
  select * into v_session from dining_sessions where session_id = p_session_id and status = 'open';
  if not found then
    raise exception 'Open dining session not found';
  end if;

  v_total :=
    v_session.adult_count * v_session.adult_price_snapshot +
    v_session.child_count * v_session.child_price_snapshot;

  update order_items
  set status = 'cancelled', cancelled_at = coalesce(cancelled_at, now())
  where order_id in (select order_id from orders where session_id = p_session_id)
    and status in ('pending', 'cooking', 'ready', 'out_for_serving');

  insert into payments (session_id, cashier_id, method, paid_amount, paid_at, status)
  values (p_session_id, p_cashier_user_id, 'cash', v_total, now(), 'paid');

  update dining_sessions
  set status = 'closed', payment_status = 'paid', closed_at = now()
  where session_id = p_session_id;

  update restaurant_tables
  set status = 'cleaning', cleaning_started_at = now()
  where table_code = v_session.table_code;

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_cashier_user_id, 'checkout_paid', 'dining_session', p_session_id::text);

  return v_total;
end;
$$;

create or replace function release_completed_cleaning_tables()
returns integer
language plpgsql
as $$
declare
  v_count integer;
begin
  update restaurant_tables
  set status = 'available', cleaning_started_at = null
  where status = 'cleaning'
    and cleaning_started_at <= now() - interval '10 minutes';

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function start_preparing_order_item(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'cooking', cooking_at = coalesce(cooking_at, now())
  where order_item_id = p_order_item_id and status = 'pending';

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'start_preparing', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function mark_order_item_ready(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'ready', ready_at = coalesce(ready_at, now())
  where order_item_id = p_order_item_id and status in ('pending', 'cooking');

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'mark_ready', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function expedite_order_item(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'ready',
      priority_level = 'rush',
      expedited_at = coalesce(expedited_at, now()),
      ready_at = coalesce(ready_at, now())
  where order_item_id = p_order_item_id
    and status in ('pending', 'cooking', 'ready');

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'expedite_order', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function send_order_item_to_table(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'out_for_serving', out_for_serving_at = coalesce(out_for_serving_at, now())
  where order_item_id = p_order_item_id and status = 'ready';

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'send_to_table', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function serve_order_item(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
declare
  v_item order_items%rowtype;
  v_recipe record;
begin
  select * into v_item from order_items where order_item_id = p_order_item_id;
  if not found or v_item.status not in ('ready', 'out_for_serving') then
    raise exception 'Only ready or out-for-serving items can be served';
  end if;

  if exists (
    select 1
    from recipes r
    join inventory_items i on i.ingredient_id = r.ingredient_id
    where r.menu_id = v_item.menu_id
      and i.deleted_at is null
      and i.quantity_on_hand < r.quantity_used * v_item.quantity
  ) then
    raise exception 'Ingredient stock is too low to serve this item';
  end if;

  for v_recipe in
    select r.ingredient_id, r.quantity_used, i.unit_cost
    from recipes r
    join inventory_items i on i.ingredient_id = r.ingredient_id
    where r.menu_id = v_item.menu_id
  loop
    update inventory_items
    set quantity_on_hand = quantity_on_hand - (v_recipe.quantity_used * v_item.quantity)
    where ingredient_id = v_recipe.ingredient_id;

    insert into inventory_transactions (
      ingredient_id,
      order_item_id,
      transaction_type,
      quantity_change,
      unit_cost_snapshot,
      occurred_at
    )
    values (
      v_recipe.ingredient_id,
      p_order_item_id,
      'usage',
      -(v_recipe.quantity_used * v_item.quantity),
      v_recipe.unit_cost,
      now()
    );
  end loop;

  update order_items
  set status = 'served',
      out_for_serving_at = coalesce(out_for_serving_at, now()),
      served_at = coalesce(served_at, now())
  where order_item_id = p_order_item_id;

  update orders
  set status = 'completed'
  where order_id = v_item.order_id
    and not exists (
      select 1 from order_items
      where order_id = v_item.order_id
        and status not in ('served', 'cancelled')
    );

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'serve_item', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function delete_all_yum_yum_buffet_data()
returns void
language plpgsql
as $$
begin
  truncate table
    inventory_transactions,
    staff_activity_logs,
    payments,
    order_items,
    orders,
    dining_sessions,
    recipes,
    menu_items,
    inventory_items,
    menu_categories,
    restaurant_tables,
    app_users
  restart identity cascade;
end;
$$;

alter table app_users disable row level security;
alter table restaurant_tables disable row level security;
alter table menu_categories disable row level security;
alter table inventory_items disable row level security;
alter table menu_items disable row level security;
alter table recipes disable row level security;
alter table dining_sessions disable row level security;
alter table orders disable row level security;
alter table order_items disable row level security;
alter table payments disable row level security;
alter table staff_activity_logs disable row level security;
alter table inventory_transactions disable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select, update on all sequences in schema public to anon, authenticated;


-- -----------------------------------------------------------------------------
-- Seed data
-- -----------------------------------------------------------------------------

-- Realistic demo seed for the simplified Yum Yum Buffet schema.
-- Run schema.sql before this file, or run reset-new-ux.sql for a full rebuild.

insert into app_users (user_id, full_name, username, password_hash, role, is_active, deleted_at) values
  ('00000000-0000-0000-0000-000000000001', 'Narin Cashier', 'cashier', 'demo-hash-cashier123', 'cashier', true, null),
  ('00000000-0000-0000-0000-000000000002', 'Ploy Kitchen', 'kitchen', 'demo-hash-kitchen123', 'kitchen', true, null),
  ('00000000-0000-0000-0000-000000000003', 'Mek Waiter', 'waiter', 'demo-hash-waiter123', 'waiter', true, null),
  ('00000000-0000-0000-0000-000000000004', 'Eddy Manager', 'manager', 'demo-hash-manager123', 'manager', true, null)
on conflict (user_id) do update set
  full_name = excluded.full_name,
  username = excluded.username,
  password_hash = excluded.password_hash,
  role = excluded.role,
  is_active = excluded.is_active,
  deleted_at = excluded.deleted_at;

insert into restaurant_tables (table_code, capacity, status, cleaning_started_at) values
  ('01', 4, 'available', null),
  ('02', 4, 'occupied', null),
  ('03', 4, 'cleaning', now() - interval '4 minutes'),
  ('04', 4, 'available', null),
  ('05', 4, 'billing', null),
  ('06', 4, 'occupied', null),
  ('07', 4, 'available', null),
  ('08', 4, 'available', null),
  ('09', 4, 'occupied', null),
  ('10', 4, 'available', null),
  ('11', 4, 'occupied', null),
  ('12', 4, 'available', null),
  ('13', 4, 'occupied', null),
  ('14', 4, 'available', null),
  ('15', 4, 'billing', null)
on conflict (table_code) do update set
  capacity = excluded.capacity,
  status = excluded.status,
  cleaning_started_at = excluded.cleaning_started_at;

insert into menu_categories (category_id, name) values
  (1, 'Pork'),
  (2, 'Beef'),
  (3, 'Seafood'),
  (4, 'Vegetables'),
  (5, 'Snacks'),
  (6, 'Drinks')
on conflict (category_id) do update set name = excluded.name;

insert into inventory_items (ingredient_id, name, unit, quantity_on_hand, reorder_level, unit_cost, deleted_at) values
  (1, 'Pork shoulder', 'g', 9200, 2500, 0.18, null),
  (2, 'Smoked bacon', 'g', 3200, 1200, 0.24, null),
  (3, 'Ribeye beef', 'g', 1800, 1500, 0.62, null),
  (4, 'Squid', 'g', 2600, 1300, 0.31, null),
  (5, 'White shrimp', 'pcs', 48, 60, 5.20, null),
  (6, 'Napa cabbage', 'g', 4200, 1800, 0.05, null),
  (7, 'Enoki mushroom', 'g', 1600, 900, 0.11, null),
  (8, 'Kimchi rice mix', 'g', 5400, 1200, 0.08, null),
  (9, 'Thai tea concentrate', 'ml', 2100, 800, 0.09, null),
  (10, 'Cola syrup', 'ml', 0, 900, 0.07, now() - interval '1 day')
on conflict (ingredient_id) do update set
  name = excluded.name,
  unit = excluded.unit,
  quantity_on_hand = excluded.quantity_on_hand,
  reorder_level = excluded.reorder_level,
  unit_cost = excluded.unit_cost,
  deleted_at = excluded.deleted_at;

insert into menu_items (menu_id, category_id, name, description, image_url, is_available, deleted_at) values
  (1, 1, 'Marinated Pork Belly', 'Soy-garlic pork belly tray', '/menu/pork-belly.svg', true, null),
  (2, 1, 'Premium Pork Shoulder', '120 g shabu pork shoulder tray', '/menu/pork-shoulder.svg', true, null),
  (3, 2, 'Black Pepper Beef', 'Pepper-crusted premium beef tray', '/menu/black-pepper-beef.svg', true, null),
  (4, 3, 'Fresh Squid', 'Cleaned squid portion', '/menu/squid.svg', true, null),
  (5, 3, 'White shrimp', 'Six shrimp per plate', '/menu/shrimp.svg', true, null),
  (6, 4, 'Napa cabbage', 'Fresh vegetable basket', '/menu/napa-cabbage.svg', true, null),
  (7, 4, 'Enoki mushroom', 'Mushroom portion', '/menu/enoki.svg', true, null),
  (8, 5, 'Kimchi fried rice', 'Small rice bowl', '/menu/kimchi-rice.svg', true, null),
  (9, 6, 'Thai iced tea', 'Refill drink glass', '/menu/thai-tea.svg', true, null),
  (10, 6, 'Cola', 'Refill drink glass', '/menu/cola.svg', false, now() - interval '1 day')
on conflict (menu_id) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  image_url = excluded.image_url,
  is_available = excluded.is_available,
  deleted_at = excluded.deleted_at;

insert into recipes (menu_id, ingredient_id, quantity_used) values
  (1, 1, 120),
  (2, 2, 90),
  (3, 3, 100),
  (4, 4, 120),
  (5, 5, 6),
  (6, 6, 150),
  (7, 7, 100),
  (8, 8, 180),
  (9, 9, 80),
  (10, 10, 70)
on conflict (menu_id, ingredient_id) do update set quantity_used = excluded.quantity_used;

insert into dining_sessions (
  session_id,
  table_code,
  cashier_id,
  adult_count,
  child_count,
  adult_price_snapshot,
  child_price_snapshot,
  opened_at,
  bill_requested_at,
  closed_at,
  status,
  payment_status
) values
  ('10000000-0000-0000-0000-000000001001', '02', '00000000-0000-0000-0000-000000000001', 3, 1, 399, 259, now() - interval '60 minutes', null, null, 'open', 'unpaid'),
  ('10000000-0000-0000-0000-000000001002', '05', '00000000-0000-0000-0000-000000000001', 2, 1, 399, 259, now() - interval '105 minutes', now() - interval '5 minutes', null, 'open', 'unpaid'),
  ('10000000-0000-0000-0000-000000001003', '06', '00000000-0000-0000-0000-000000000001', 2, 0, 399, 259, now() - interval '23 minutes', null, null, 'open', 'unpaid'),
  ('10000000-0000-0000-0000-000000001004', '09', '00000000-0000-0000-0000-000000000001', 4, 0, 399, 259, now() - interval '72 minutes', null, null, 'open', 'unpaid'),
  ('10000000-0000-0000-0000-000000001005', '11', '00000000-0000-0000-0000-000000000001', 2, 2, 399, 259, now() - interval '45 minutes', null, null, 'open', 'unpaid'),
  ('10000000-0000-0000-0000-000000001006', '13', '00000000-0000-0000-0000-000000000001', 4, 0, 399, 259, now() - interval '68 minutes', null, null, 'open', 'unpaid'),
  ('10000000-0000-0000-0000-000000001007', '15', '00000000-0000-0000-0000-000000000001', 4, 0, 399, 259, now() - interval '94 minutes', now() - interval '3 minutes', null, 'open', 'unpaid'),
  ('10000000-0000-0000-0000-000000001008', '04', '00000000-0000-0000-0000-000000000001', 2, 0, 399, 259, now() - interval '260 minutes', now() - interval '160 minutes', now() - interval '155 minutes', 'closed', 'paid'),
  ('10000000-0000-0000-0000-000000001009', '12', '00000000-0000-0000-0000-000000000001', 2, 2, 399, 259, now() - interval '1380 minutes', now() - interval '1290 minutes', now() - interval '1285 minutes', 'closed', 'paid')
on conflict (session_id) do update set
  table_code = excluded.table_code,
  cashier_id = excluded.cashier_id,
  adult_count = excluded.adult_count,
  child_count = excluded.child_count,
  adult_price_snapshot = excluded.adult_price_snapshot,
  child_price_snapshot = excluded.child_price_snapshot,
  opened_at = excluded.opened_at,
  bill_requested_at = excluded.bill_requested_at,
  closed_at = excluded.closed_at,
  status = excluded.status,
  payment_status = excluded.payment_status;

insert into orders (order_id, session_id, ordered_at, status) values
  (1001, '10000000-0000-0000-0000-000000001001', now() - interval '36 minutes', 'open'),
  (1002, '10000000-0000-0000-0000-000000001001', now() - interval '15 minutes', 'open'),
  (1003, '10000000-0000-0000-0000-000000001002', now() - interval '240 minutes', 'completed'),
  (1004, '10000000-0000-0000-0000-000000001003', now() - interval '1360 minutes', 'completed'),
  (1005, '10000000-0000-0000-0000-000000001003', now() - interval '1342 minutes', 'completed')
on conflict (order_id) do update set
  session_id = excluded.session_id,
  ordered_at = excluded.ordered_at,
  status = excluded.status;

insert into order_items (
  order_item_id,
  order_id,
  menu_id,
  quantity,
  status,
  special_instructions,
  priority_level,
  expedited_at,
  requested_at,
  cooking_at,
  ready_at,
  out_for_serving_at,
  served_at,
  cancelled_at
) values
  (1001, 1001, 1, 2, 'cooking', 'Thin slice, no spicy sauce', 'normal', null, now() - interval '36 minutes', now() - interval '31 minutes', null, null, null, null),
  (1002, 1001, 6, 1, 'ready', 'Extra fresh basket', 'rush', now() - interval '20 minutes', now() - interval '36 minutes', now() - interval '32 minutes', now() - interval '27 minutes', null, null, null),
  (1003, 1002, 3, 1, 'pending', 'Chef priority for premium add-on', 'rush', now() - interval '8 minutes', now() - interval '24 minutes', null, null, null, null, null),
  (1004, 1002, 5, 2, 'pending', 'Serve chilled', 'normal', null, now() - interval '15 minutes', null, null, null, null, null),
  (1005, 1003, 1, 3, 'served', '', 'normal', null, now() - interval '240 minutes', now() - interval '235 minutes', now() - interval '230 minutes', now() - interval '228 minutes', now() - interval '226 minutes', null),
  (1006, 1003, 8, 2, 'served', 'Less spicy', 'normal', null, now() - interval '240 minutes', now() - interval '234 minutes', now() - interval '229 minutes', now() - interval '227 minutes', now() - interval '225 minutes', null),
  (1007, 1004, 2, 4, 'served', '', 'normal', null, now() - interval '1360 minutes', now() - interval '1354 minutes', now() - interval '1348 minutes', now() - interval '1347 minutes', now() - interval '1345 minutes', null),
  (1008, 1004, 4, 2, 'served', '', 'normal', null, now() - interval '1360 minutes', now() - interval '1355 minutes', now() - interval '1349 minutes', now() - interval '1348 minutes', now() - interval '1346 minutes', null),
  (1009, 1005, 5, 3, 'served', 'Extra sauce', 'normal', null, now() - interval '1342 minutes', now() - interval '1338 minutes', now() - interval '1332 minutes', now() - interval '1330 minutes', now() - interval '1328 minutes', null),
  (1010, 1005, 9, 4, 'served', '', 'normal', null, now() - interval '1342 minutes', now() - interval '1339 minutes', now() - interval '1335 minutes', now() - interval '1333 minutes', now() - interval '1331 minutes', null)
on conflict (order_item_id) do update set
  order_id = excluded.order_id,
  menu_id = excluded.menu_id,
  quantity = excluded.quantity,
  status = excluded.status,
  special_instructions = excluded.special_instructions,
  priority_level = excluded.priority_level,
  expedited_at = excluded.expedited_at,
  requested_at = excluded.requested_at,
  cooking_at = excluded.cooking_at,
  ready_at = excluded.ready_at,
  out_for_serving_at = excluded.out_for_serving_at,
  served_at = excluded.served_at,
  cancelled_at = excluded.cancelled_at;

insert into payments (payment_id, session_id, cashier_id, method, paid_amount, paid_at, status) values
  (1, '10000000-0000-0000-0000-000000001008', '00000000-0000-0000-0000-000000000001', 'cash', 798, now() - interval '155 minutes', 'paid'),
  (2, '10000000-0000-0000-0000-000000001009', '00000000-0000-0000-0000-000000000001', 'cash', 2114, now() - interval '1285 minutes', 'paid')
on conflict (payment_id) do update set
  session_id = excluded.session_id,
  cashier_id = excluded.cashier_id,
  method = excluded.method,
  paid_amount = excluded.paid_amount,
  paid_at = excluded.paid_at,
  status = excluded.status;

insert into staff_activity_logs (activity_id, user_id, action, entity_type, entity_id, occurred_at) values
  (1, '00000000-0000-0000-0000-000000000001', 'open_table', 'dining_session', '10000000-0000-0000-0000-000000001008', now() - interval '260 minutes'),
  (2, '00000000-0000-0000-0000-000000000001', 'checkout_paid', 'payment', '1', now() - interval '155 minutes'),
  (3, '00000000-0000-0000-0000-000000000003', 'serve_item', 'order_item', '1005', now() - interval '226 minutes'),
  (4, '00000000-0000-0000-0000-000000000002', 'start_preparing', 'order_item', '1001', now() - interval '31 minutes'),
  (5, '00000000-0000-0000-0000-000000000002', 'expedite_order', 'order_item', '1003', now() - interval '8 minutes')
on conflict (activity_id) do update set
  user_id = excluded.user_id,
  action = excluded.action,
  entity_type = excluded.entity_type,
  entity_id = excluded.entity_id,
  occurred_at = excluded.occurred_at;

insert into inventory_transactions (transaction_id, ingredient_id, order_item_id, transaction_type, quantity_change, unit_cost_snapshot, occurred_at) values
  (1, 1, 1005, 'usage', -360, 0.18, now() - interval '226 minutes'),
  (2, 8, 1006, 'usage', -360, 0.08, now() - interval '225 minutes'),
  (3, 2, 1007, 'usage', -360, 0.24, now() - interval '1345 minutes'),
  (4, 4, 1008, 'usage', -240, 0.31, now() - interval '1346 minutes'),
  (5, 5, 1009, 'usage', -18, 5.20, now() - interval '1328 minutes'),
  (6, 9, 1010, 'usage', -320, 0.09, now() - interval '1331 minutes')
on conflict (transaction_id) do update set
  ingredient_id = excluded.ingredient_id,
  order_item_id = excluded.order_item_id,
  transaction_type = excluded.transaction_type,
  quantity_change = excluded.quantity_change,
  unit_cost_snapshot = excluded.unit_cost_snapshot,
  occurred_at = excluded.occurred_at;

select setval(pg_get_serial_sequence('menu_categories', 'category_id'), 6, true);
select setval(pg_get_serial_sequence('inventory_items', 'ingredient_id'), 10, true);
select setval(pg_get_serial_sequence('menu_items', 'menu_id'), 10, true);
select setval(pg_get_serial_sequence('orders', 'order_id'), 1005, true);
select setval(pg_get_serial_sequence('order_items', 'order_item_id'), 1010, true);
select setval(pg_get_serial_sequence('payments', 'payment_id'), 2, true);
select setval(pg_get_serial_sequence('staff_activity_logs', 'activity_id'), 5, true);
select setval(pg_get_serial_sequence('inventory_transactions', 'transaction_id'), 6, true);
