-- The Nocturnal Epicurean schema for PostgreSQL / Supabase.
-- Run this file first in a fresh Supabase SQL editor.

-- Supabase already supports pgcrypto in most projects; this enables gen_random_uuid().
create extension if not exists "pgcrypto";

-- Enum creation is wrapped so rerunning the script does not fail on existing types.
do $$
begin
  create type staff_role as enum ('cashier', 'kitchen', 'waiter', 'manager');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type table_status as enum ('available', 'occupied', 'cleaning', 'billing', 'disabled');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type session_status as enum ('open', 'closed', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type payment_status as enum ('unpaid', 'paid', 'refunded');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type payment_method as enum ('cash');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type order_status as enum ('open', 'completed', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type order_item_status as enum ('pending', 'cooking', 'ready', 'out_for_serving', 'served', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type order_priority as enum ('normal', 'rush');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type order_source as enum ('customer', 'cashier');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type inventory_transaction_type as enum ('purchase', 'usage', 'adjustment', 'waste');
exception when duplicate_object then null;
end $$;

-- Staff users hold every login role required by the UX feedback.
create table if not exists app_users (
  user_id uuid primary key default gen_random_uuid(),
  full_name varchar(120) not null,
  username varchar(60) not null unique,
  password_hash text not null,
  role staff_role not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

comment on table app_users is 'Staff login table for cashier, kitchen, waiter, and manager roles. Customers do not log in.';
comment on column app_users.deleted_at is 'Soft delete timestamp; inactive staff stay available for historical cashier/order references.';

-- Staff shifts are created immediately after successful staff authentication.
create table if not exists staff_shifts (
  shift_id bigint generated by default as identity primary key,
  user_id uuid not null references app_users(user_id),
  role_snapshot staff_role not null,
  station varchar(80) not null,
  clock_in_at timestamptz not null default now(),
  clock_out_at timestamptz,
  login_at timestamptz not null default now(),
  logout_at timestamptz,
  note text not null default '',
  check (clock_out_at is null or clock_out_at >= clock_in_at),
  check (logout_at is null or logout_at >= login_at)
);

comment on table staff_shifts is 'Clock-in/clock-out history created by the staff portal for work-hour reporting and staff accountability.';
comment on column staff_shifts.role_snapshot is 'Copies the role at login time so historical shifts stay correct even if a staff role changes later.';
comment on column staff_shifts.station is 'Work station chosen from the login role, such as Front POS, Kitchen pass, Dining room, or Management office.';

-- Staff activity logs connect operational actions to the authenticated user and active shift.
create table if not exists staff_activity_logs (
  activity_id bigint generated by default as identity primary key,
  user_id uuid not null references app_users(user_id),
  shift_id bigint references staff_shifts(shift_id),
  action varchar(80) not null,
  entity_type varchar(40) not null,
  entity_id text not null,
  occurred_at timestamptz not null default now(),
  note text not null default ''
);

comment on table staff_activity_logs is 'Audit trail for login, order, kitchen, payment, inventory, and manager actions.';
comment on column staff_activity_logs.entity_type is 'Table or business object affected, for example dining_session, order_item, payment, menu_item, or inventory_item.';

-- Restaurant tables are assigned to exactly one open dining session at a time.
create table if not exists restaurant_tables (
  table_id bigint generated by default as identity primary key,
  table_code varchar(12) not null unique,
  zone varchar(40) not null,
  capacity integer not null default 4 check (capacity = 4),
  status table_status not null default 'available',
  cleaning_started_at timestamptz,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

comment on table restaurant_tables is 'Physical dine-in tables that cashiers open and release.';
comment on column restaurant_tables.status is 'available means ready for check-in; occupied means guests are seated; billing means cash payment is pending; cleaning means the 10-minute reset timer is running.';
comment on column restaurant_tables.cleaning_started_at is 'Set when cash checkout moves a table to cleaning; when 10 minutes pass the app or a scheduled job should mark it available.';

-- Dining sessions are the main transaction boundary for buffet guests.
create table if not exists dining_sessions (
  session_id uuid primary key default gen_random_uuid(),
  table_id bigint not null references restaurant_tables(table_id),
  cashier_id uuid not null references app_users(user_id),
  waiter_id uuid references app_users(user_id),
  adult_count integer not null default 0 check (adult_count >= 0),
  child_count integer not null default 0 check (child_count >= 0),
  adult_price numeric(10,2) not null default 0 check (adult_price >= 0),
  child_price numeric(10,2) not null default 0 check (child_price >= 0),
  opened_at timestamptz not null default now(),
  bill_requested_at timestamptz,
  closed_at timestamptz,
  status session_status not null default 'open',
  payment_status payment_status not null default 'unpaid',
  customer_code varchar(20) not null unique,
  check (adult_count + child_count > 0),
  check (adult_count + child_count <= 4)
);

comment on table dining_sessions is 'One buffet visit for one table; stores guest counts and prices needed for revenue and cost-per-head reports.';
comment on column dining_sessions.opened_at is 'Used for peak-hour and average dining-time dashboard queries.';
comment on column dining_sessions.bill_requested_at is 'Set when guests request a cash bill; drives the cashier payment state.';
comment on column dining_sessions.closed_at is 'Filled when cashier closes and pays the session.';

-- Payments store cashier checkout data separately from sessions.
create table if not exists payments (
  payment_id bigint generated by default as identity primary key,
  session_id uuid not null unique references dining_sessions(session_id),
  cashier_id uuid not null references app_users(user_id),
  method payment_method not null,
  paid_amount numeric(10,2) not null check (paid_amount >= 0),
  paid_at timestamptz not null default now(),
  status payment_status not null default 'paid'
);

comment on table payments is 'Cash-only payment rows support daily revenue reports and cashier audit history.';

-- Menu categories keep the customer menu query grouped and readable.
create table if not exists menu_categories (
  category_id bigint generated by default as identity primary key,
  name varchar(80) not null unique
);

comment on table menu_categories is 'Category lookup table for menu browsing and reporting.';

-- Menu items are soft-deleted instead of physically removed.
create table if not exists menu_items (
  menu_id bigint generated by default as identity primary key,
  category_id bigint not null references menu_categories(category_id),
  name varchar(120) not null,
  description text not null default '',
  image_url text not null default '',
  kitchen_station varchar(60) not null default 'general',
  prep_time_minutes integer not null default 5 check (prep_time_minutes > 0),
  price numeric(10,2) not null default 0 check (price >= 0),
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

comment on table menu_items is 'Food and drink items customers can order; deleted_at supports the removed-list requirement.';
comment on column menu_items.image_url is 'Menu image path or Supabase Storage URL used by customer ordering and menu dashboards.';
comment on column menu_items.kitchen_station is 'Preparation station used to route or filter kitchen display cards.';
comment on column menu_items.prep_time_minutes is 'Target preparation time used for late-order warnings.';
comment on column menu_items.price is 'Add-on price; buffet-included items can stay at 0.';

-- Orders group several order_items submitted from one customer action.
create table if not exists orders (
  order_id bigint generated by default as identity primary key,
  session_id uuid not null references dining_sessions(session_id),
  ordered_at timestamptz not null default now(),
  source order_source not null default 'customer',
  status order_status not null default 'open',
  note text not null default ''
);

comment on table orders is 'Customer order header tied to one active dining session.';

-- Order items are the operational queue rows for kitchen and waiter.
create table if not exists order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references orders(order_id),
  menu_id bigint not null references menu_items(menu_id),
  quantity integer not null check (quantity > 0),
  status order_item_status not null default 'pending',
  special_instructions text not null default '',
  priority_level order_priority not null default 'normal',
  priority_reason text not null default '',
  expedited_at timestamptz,
  requested_at timestamptz not null default now(),
  cooking_at timestamptz,
  ready_at timestamptz,
  out_for_serving_at timestamptz,
  served_at timestamptz,
  cancelled_at timestamptz
);

comment on table order_items is 'Kitchen/waiter queue rows; timestamps are required for average service-speed reports.';
comment on column order_items.special_instructions is 'Customer or cashier item-level notes shown on the kitchen display card.';
comment on column order_items.priority_level is 'Rush priority flag for red KDS cards and chef-priority reporting.';
comment on column order_items.expedited_at is 'Timestamp when staff escalated an order item.';
comment on column order_items.out_for_serving_at is 'Timestamp when a waiter picked up ready food so customer iPads can show out for serving.';

-- Inventory items keep current stock and cost values for low-stock and cost reports.
create table if not exists inventory_items (
  ingredient_id bigint generated by default as identity primary key,
  name varchar(120) not null unique,
  unit varchar(20) not null,
  quantity_on_hand numeric(12,2) not null default 0 check (quantity_on_hand >= 0),
  reorder_level numeric(12,2) not null default 0 check (reorder_level >= 0),
  unit_cost numeric(10,4) not null default 0 check (unit_cost >= 0),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

comment on table inventory_items is 'Ingredients and materials used by recipes; quantity_on_hand powers low-stock alerts.';
comment on column inventory_items.unit_cost is 'Cost per inventory unit, copied into transactions for historical cost accuracy.';

-- Recipes map many menu items to many inventory items.
create table if not exists recipes (
  recipe_id bigint generated by default as identity primary key,
  menu_id bigint not null references menu_items(menu_id),
  ingredient_id bigint not null references inventory_items(ingredient_id),
  quantity_used numeric(12,2) not null check (quantity_used > 0),
  unique (menu_id, ingredient_id)
);

comment on table recipes is 'Recipe mapping table used to deduct stock when a waiter marks an item as served.';

-- Inventory transactions are the audit trail for usage, purchases, adjustments, and waste.
create table if not exists inventory_transactions (
  transaction_id bigint generated by default as identity primary key,
  ingredient_id bigint not null references inventory_items(ingredient_id),
  order_item_id bigint references order_items(order_item_id),
  staff_id uuid references app_users(user_id),
  transaction_type inventory_transaction_type not null,
  quantity_change numeric(12,2) not null,
  unit_cost_snapshot numeric(10,4) not null default 0,
  occurred_at timestamptz not null default now(),
  note text not null default ''
);

comment on table inventory_transactions is 'Stock movement history for ingredient usage, purchase, adjustment, and waste reports.';
comment on column inventory_transactions.quantity_change is 'Positive means stock increased; negative means stock decreased.';

-- Integrity and performance indexes for the interface queries.
create unique index if not exists uq_open_session_per_table
  on dining_sessions(table_id)
  where status = 'open';

create unique index if not exists uq_active_shift_per_user
  on staff_shifts(user_id)
  where clock_out_at is null;

create index if not exists idx_tables_active_status
  on restaurant_tables(status, table_code)
  where deleted_at is null;

create index if not exists idx_sessions_table_status_opened
  on dining_sessions(table_id, status, opened_at desc);

create index if not exists idx_sessions_status_payment_bill
  on dining_sessions(status, payment_status, bill_requested_at);

create index if not exists idx_sessions_opened_at
  on dining_sessions(opened_at);

create index if not exists idx_payments_status_paid_at
  on payments(status, paid_at desc);

create index if not exists idx_orders_session_ordered
  on orders(session_id, ordered_at);

create index if not exists idx_order_items_status_requested
  on order_items(status, requested_at);

create index if not exists idx_order_items_order_status
  on order_items(order_id, status);

create index if not exists idx_order_items_menu_id
  on order_items(menu_id);

create index if not exists idx_order_items_priority
  on order_items(priority_level, requested_at);

create index if not exists idx_menu_items_active_category
  on menu_items(category_id, name)
  where deleted_at is null and is_available = true;

create index if not exists idx_menu_items_station
  on menu_items(kitchen_station)
  where deleted_at is null;

create index if not exists idx_inventory_items_stock
  on inventory_items(deleted_at, quantity_on_hand);

create index if not exists idx_recipes_menu_id
  on recipes(menu_id);

create index if not exists idx_recipes_ingredient_id
  on recipes(ingredient_id);

create index if not exists idx_transactions_type_occurred
  on inventory_transactions(transaction_type, occurred_at desc);

create index if not exists idx_transactions_ingredient_occurred
  on inventory_transactions(ingredient_id, occurred_at desc);

create index if not exists idx_staff_shifts_user_clock
  on staff_shifts(user_id, clock_in_at desc);

create index if not exists idx_staff_shifts_active
  on staff_shifts(user_id, clock_in_at desc)
  where clock_out_at is null;

create index if not exists idx_staff_activity_user_id
  on staff_activity_logs(user_id);

create index if not exists idx_staff_activity_shift_id
  on staff_activity_logs(shift_id);

create index if not exists idx_staff_activity_occurred_desc
  on staff_activity_logs(occurred_at desc);

-- Small helper reused by operational RPC functions.
create or replace function active_shift_id(p_staff_id uuid)
returns bigint
language sql
stable
as $$
  select shift_id
  from staff_shifts
  where user_id = p_staff_id
    and clock_out_at is null
  order by clock_in_at desc
  limit 1
$$;

comment on function active_shift_id(uuid) is 'Returns the latest open shift for audit-log writes.';

-- Inventory can hide iPad menu rows automatically when linked ingredients hit zero.
create or replace function sync_menu_availability_for_stock(p_ingredient_id bigint)
returns void
language sql
as $$
  update menu_items m
  set is_available = false
  where m.deleted_at is null
    and exists (
      select 1
      from recipes touched
      where touched.menu_id = m.menu_id
        and touched.ingredient_id = p_ingredient_id
    )
    and exists (
      select 1
      from recipes r
      join inventory_items i on i.ingredient_id = r.ingredient_id
      where r.menu_id = m.menu_id
        and (i.deleted_at is not null or i.quantity_on_hand <= 0)
    );
$$;

comment on function sync_menu_availability_for_stock(bigint) is 'Hides linked customer iPad menu rows when any recipe ingredient is out of stock.';

-- Manager inventory kiosk toggle: hide/show every iPad item linked to one ingredient.
create or replace function set_menu_availability_for_ingredient(
  p_ingredient_id bigint,
  p_is_available boolean,
  p_staff_id uuid
)
returns void
language plpgsql
as $$
declare
  v_ingredient inventory_items%rowtype;
  v_menu_id bigint;
begin
  select *
  into v_ingredient
  from inventory_items
  where ingredient_id = p_ingredient_id
  for update;

  if not found then
    raise exception 'Ingredient % does not exist', p_ingredient_id;
  end if;

  if p_is_available and (v_ingredient.deleted_at is not null or v_ingredient.quantity_on_hand <= 0) then
    raise exception 'Restock % before showing linked iPad menu items', v_ingredient.name;
  end if;

  update menu_items m
  set is_available = p_is_available
  where exists (
    select 1
    from recipes r
    where r.menu_id = m.menu_id
      and r.ingredient_id = p_ingredient_id
  );

  if p_is_available then
    for v_menu_id in
      select distinct r.menu_id
      from recipes r
      where r.ingredient_id = p_ingredient_id
    loop
      perform sync_menu_availability_for_stock(r.ingredient_id)
      from recipes r
      where r.menu_id = v_menu_id;
    end loop;
  end if;

  insert into staff_activity_logs (user_id, shift_id, action, entity_type, entity_id, occurred_at, note)
  values (
    p_staff_id,
    active_shift_id(p_staff_id),
    'toggle_kiosk_menu_from_inventory',
    'inventory_item',
    p_ingredient_id::text,
    now(),
    v_ingredient.name || ' linked iPad menu availability set to ' || p_is_available::text
  );
end;
$$;

comment on function set_menu_availability_for_ingredient(bigint, boolean, uuid) is 'Manager action: toggles customer iPad visibility for menu items that depend on an ingredient.';

-- Cleaning timer helper for the cashier table-management flow.
-- The frontend also checks this, but keeping it in SQL makes the data rule explicit.
create or replace function release_completed_cleaning_tables()
returns integer
language plpgsql
as $$
declare
  v_released_count integer;
begin
  update restaurant_tables
  set status = 'available',
      cleaning_started_at = null
  where status = 'cleaning'
    and cleaning_started_at is not null
    and cleaning_started_at <= now() - interval '10 minutes';

  get diagnostics v_released_count = row_count;
  return v_released_count;
end;
$$;

comment on function release_completed_cleaning_tables() is 'Returns cleaning tables to available after the 10-minute cashier cleanup timer expires.';

-- Manual stock adjustment used by the manager inventory screen.
create or replace function adjust_inventory_stock(
  p_ingredient_id bigint,
  p_quantity_change numeric,
  p_staff_id uuid,
  p_note text default 'Manual inventory adjustment'
)
returns void
language plpgsql
as $$
declare
  v_ingredient inventory_items%rowtype;
  v_next_quantity numeric(12,2);
begin
  select *
  into v_ingredient
  from inventory_items
  where ingredient_id = p_ingredient_id
  for update;

  if not found then
    raise exception 'Ingredient % does not exist', p_ingredient_id;
  end if;

  v_next_quantity := v_ingredient.quantity_on_hand + p_quantity_change;

  if v_next_quantity < 0 then
    raise exception 'Stock movement would make % negative', v_ingredient.name;
  end if;

  update inventory_items
  set quantity_on_hand = v_next_quantity
  where ingredient_id = p_ingredient_id;

  insert into inventory_transactions (
    ingredient_id,
    order_item_id,
    staff_id,
    transaction_type,
    quantity_change,
    unit_cost_snapshot,
    occurred_at,
    note
  )
  values (
    p_ingredient_id,
    null,
    p_staff_id,
    case when p_quantity_change >= 0 then 'adjustment'::inventory_transaction_type else 'waste'::inventory_transaction_type end,
    p_quantity_change,
    v_ingredient.unit_cost,
    now(),
    p_note
  );

  perform sync_menu_availability_for_stock(p_ingredient_id);

  insert into staff_activity_logs (user_id, shift_id, action, entity_type, entity_id, occurred_at, note)
  values (
    p_staff_id,
    active_shift_id(p_staff_id),
    'quick_stock_adjustment',
    'inventory_item',
    p_ingredient_id::text,
    now(),
    v_ingredient.name || ' stock changed by ' || p_quantity_change::text || ' ' || v_ingredient.unit
  );
end;
$$;

comment on function adjust_inventory_stock(bigint, numeric, uuid, text) is 'Manager action: adjusts stock, writes a transaction, and hides linked menu items if stock reaches zero.';

-- Kitchen status functions match the KDS card buttons.
create or replace function start_preparing_order_item(p_order_item_id bigint, p_staff_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'cooking',
      cooking_at = coalesce(cooking_at, now())
  where order_item_id = p_order_item_id
    and status = 'pending';

  if not found then
    raise exception 'Order item % must be pending before preparation starts', p_order_item_id;
  end if;

  insert into staff_activity_logs (user_id, shift_id, action, entity_type, entity_id, occurred_at, note)
  values (p_staff_id, active_shift_id(p_staff_id), 'start_preparing', 'order_item', p_order_item_id::text, now(), 'Kitchen started preparing item');
end;
$$;

comment on function start_preparing_order_item(bigint, uuid) is 'Kitchen action: moves a new white KDS card into yellow PREPARING state.';

create or replace function mark_order_item_ready(p_order_item_id bigint, p_staff_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'ready',
      ready_at = coalesce(ready_at, now())
  where order_item_id = p_order_item_id
    and status in ('pending', 'cooking');

  if not found then
    raise exception 'Order item % must be pending or cooking before it can be ready', p_order_item_id;
  end if;

  insert into staff_activity_logs (user_id, shift_id, action, entity_type, entity_id, occurred_at, note)
  values (p_staff_id, active_shift_id(p_staff_id), 'mark_ready', 'order_item', p_order_item_id::text, now(), 'Kitchen marked item ready for waiter');
end;
$$;

comment on function mark_order_item_ready(bigint, uuid) is 'Kitchen action: moves food into blue READY state for waiter pickup.';

create or replace function expedite_order_item(
  p_order_item_id bigint,
  p_staff_id uuid,
  p_reason text default 'EXPEDITE NOW!!'
)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'ready',
      priority_level = 'rush',
      priority_reason = p_reason,
      expedited_at = coalesce(expedited_at, now()),
      ready_at = coalesce(ready_at, now())
  where order_item_id = p_order_item_id
    and status in ('pending', 'cooking');

  if not found then
    raise exception 'Order item % cannot be expedited in its current state', p_order_item_id;
  end if;

  insert into staff_activity_logs (user_id, shift_id, action, entity_type, entity_id, occurred_at, note)
  values (p_staff_id, active_shift_id(p_staff_id), 'expedite_order', 'order_item', p_order_item_id::text, now(), p_reason);
end;
$$;

comment on function expedite_order_item(bigint, uuid, text) is 'Kitchen action: flags a waiting item as red rush priority and moves it straight to ready-for-server.';

-- Cashier payment helpers match the new billing flow.
create or replace function request_cash_bill(p_session_id uuid, p_cashier_id uuid)
returns void
language plpgsql
as $$
declare
  v_session dining_sessions%rowtype;
begin
  select *
  into v_session
  from dining_sessions
  where session_id = p_session_id
    and status = 'open'
  for update;

  if not found then
    raise exception 'Open dining session % does not exist', p_session_id;
  end if;

  update dining_sessions
  set bill_requested_at = coalesce(bill_requested_at, now())
  where session_id = p_session_id;

  update restaurant_tables
  set status = 'billing'
  where table_id = v_session.table_id;

  insert into staff_activity_logs (user_id, shift_id, action, entity_type, entity_id, occurred_at, note)
  values (p_cashier_id, active_shift_id(p_cashier_id), 'request_bill', 'dining_session', p_session_id::text, now(), 'Cash bill requested');
end;
$$;

comment on function request_cash_bill(uuid, uuid) is 'Cashier action: moves an open table into the red billing payment state.';

create or replace function cash_checkout_session(
  p_session_id uuid,
  p_cashier_id uuid,
  p_paid_amount numeric default null
)
returns void
language plpgsql
as $$
declare
  v_session dining_sessions%rowtype;
  v_paid_amount numeric(10,2);
  v_cancelled_count integer;
begin
  select *
  into v_session
  from dining_sessions
  where session_id = p_session_id
    and status = 'open'
  for update;

  if not found then
    raise exception 'Open dining session % does not exist', p_session_id;
  end if;

  v_paid_amount := coalesce(
    p_paid_amount,
    v_session.adult_count * v_session.adult_price + v_session.child_count * v_session.child_price
  );

  update order_items oi
  set status = 'cancelled',
      cancelled_at = coalesce(cancelled_at, now())
  from orders o
  where o.order_id = oi.order_id
    and o.session_id = p_session_id
    and oi.status in ('pending', 'cooking', 'ready', 'out_for_serving');

  get diagnostics v_cancelled_count = row_count;

  insert into payments (session_id, cashier_id, method, paid_amount, paid_at, status)
  values (p_session_id, p_cashier_id, 'cash', v_paid_amount, now(), 'paid')
  on conflict (session_id) do update
    set cashier_id = excluded.cashier_id,
        method = excluded.method,
        paid_amount = excluded.paid_amount,
        paid_at = excluded.paid_at,
        status = excluded.status;

  update dining_sessions
  set status = 'closed',
      payment_status = 'paid',
      closed_at = coalesce(closed_at, now())
  where session_id = p_session_id;

  update restaurant_tables
  set status = 'cleaning',
      cleaning_started_at = now()
  where table_id = v_session.table_id;

  update orders
  set status = 'completed'
  where session_id = p_session_id
    and not exists (
      select 1
      from order_items oi
      where oi.order_id = orders.order_id
        and oi.status in ('pending', 'cooking', 'ready', 'out_for_serving')
    );

  insert into staff_activity_logs (user_id, shift_id, action, entity_type, entity_id, occurred_at, note)
  values (
    p_cashier_id,
    active_shift_id(p_cashier_id),
    'checkout_paid',
    'dining_session',
    p_session_id::text,
    now(),
    'Cash checkout completed; cancelled unfinished kitchen items: ' || v_cancelled_count::text
  );
end;
$$;

comment on function cash_checkout_session(uuid, uuid, numeric) is 'Cashier action: cash-only payment, cancels unfinished items, closes the session, and starts the 10-minute cleaning timer.';

-- This function moves ready kitchen food into the waiter delivery state.
create or replace function send_order_item_to_table(p_order_item_id bigint, p_staff_id uuid)
returns void
language plpgsql
as $$
declare
  v_item order_items%rowtype;
  v_shift_id bigint;
begin
  select *
  into v_item
  from order_items
  where order_item_id = p_order_item_id
  for update;

  if not found then
    raise exception 'Order item % does not exist', p_order_item_id;
  end if;

  if v_item.status <> 'ready' then
    raise exception 'Order item % must be ready before it can be sent out', p_order_item_id;
  end if;

  update order_items
  set status = 'out_for_serving',
      out_for_serving_at = now()
  where order_item_id = p_order_item_id;

  select shift_id
  into v_shift_id
  from staff_shifts
  where user_id = p_staff_id
    and clock_out_at is null
  order by clock_in_at desc
  limit 1;

  insert into staff_activity_logs (
    user_id,
    shift_id,
    action,
    entity_type,
    entity_id,
    occurred_at,
    note
  )
  values (
    p_staff_id,
    v_shift_id,
    'send_to_table',
    'order_item',
    p_order_item_id::text,
    now(),
    'Waiter picked up item; customer iPad now shows out for serving'
  );
end;
$$;

comment on function send_order_item_to_table(bigint, uuid) is 'Waiter action: ready food leaves the kitchen pass and becomes visible to customers as out for serving.';

-- This function makes the served action safe: check stock, deduct inventory, then mark served.
create or replace function serve_order_item(p_order_item_id bigint, p_staff_id uuid)
returns void
language plpgsql
as $$
declare
  v_item order_items%rowtype;
  v_recipe record;
  v_required numeric(12,2);
  v_shift_id bigint;
begin
  select *
  into v_item
  from order_items
  where order_item_id = p_order_item_id
  for update;

  if not found then
    raise exception 'Order item % does not exist', p_order_item_id;
  end if;

  if v_item.status <> 'out_for_serving' then
    raise exception 'Order item % must be out for serving before it can be served', p_order_item_id;
  end if;

  for v_recipe in
    select r.ingredient_id, r.quantity_used, i.quantity_on_hand, i.name, i.unit_cost
    from recipes r
    join inventory_items i on i.ingredient_id = r.ingredient_id
    where r.menu_id = v_item.menu_id
    for update of i
  loop
    v_required := v_recipe.quantity_used * v_item.quantity;

    if v_recipe.quantity_on_hand < v_required then
      raise exception 'Not enough stock for %. Required %, available %', v_recipe.name, v_required, v_recipe.quantity_on_hand;
    end if;
  end loop;

  for v_recipe in
    select r.ingredient_id, r.quantity_used, i.unit_cost
    from recipes r
    join inventory_items i on i.ingredient_id = r.ingredient_id
    where r.menu_id = v_item.menu_id
    for update of i
  loop
    v_required := v_recipe.quantity_used * v_item.quantity;

    update inventory_items
    set quantity_on_hand = quantity_on_hand - v_required
    where ingredient_id = v_recipe.ingredient_id;

    insert into inventory_transactions (
      ingredient_id,
      order_item_id,
      staff_id,
      transaction_type,
      quantity_change,
      unit_cost_snapshot,
      occurred_at,
      note
    )
    values (
      v_recipe.ingredient_id,
      p_order_item_id,
      p_staff_id,
      'usage',
      -v_required,
      v_recipe.unit_cost,
      now(),
      'Served order item'
    );

    perform sync_menu_availability_for_stock(v_recipe.ingredient_id);
  end loop;

  update order_items
  set status = 'served',
      served_at = now()
  where order_item_id = p_order_item_id;

  select shift_id
  into v_shift_id
  from staff_shifts
  where user_id = p_staff_id
    and clock_out_at is null
  order by clock_in_at desc
  limit 1;

  insert into staff_activity_logs (
    user_id,
    shift_id,
    action,
    entity_type,
    entity_id,
    occurred_at,
    note
  )
  values (
    p_staff_id,
    v_shift_id,
    'serve_item',
    'order_item',
    p_order_item_id::text,
    now(),
    'Waiter marked item served and inventory was deducted'
  );

  update orders
  set status = 'completed'
  where order_id = v_item.order_id
    and not exists (
      select 1
      from order_items oi
      where oi.order_id = v_item.order_id
        and oi.status in ('pending', 'cooking', 'ready', 'out_for_serving')
    );
end;
$$;

comment on function serve_order_item(bigint, uuid) is 'Atomic waiter action: verify recipe stock, deduct inventory, write transactions, and mark the order item served.';

-- The class demo uses app_users for staff login, not Supabase Auth.
-- These grants let the deployed browser app read and write the project tables with the anon key.
alter table app_users disable row level security;
alter table staff_shifts disable row level security;
alter table restaurant_tables disable row level security;
alter table menu_categories disable row level security;
alter table inventory_items disable row level security;
alter table menu_items disable row level security;
alter table recipes disable row level security;
alter table dining_sessions disable row level security;
alter table orders disable row level security;
alter table order_items disable row level security;
alter table payments disable row level security;
alter table staff_activity_logs disable row level security;
alter table inventory_transactions disable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select, update on all sequences in schema public to anon, authenticated;
