-- Yum Yum Buffet - simplified Supabase schema.
-- This file is schema-only. For a full rebuild with data, run reset-new-ux.sql.

create extension if not exists pgcrypto;

do $$ begin create type app_role as enum ('cashier', 'kitchen', 'waiter', 'manager'); exception when duplicate_object then null; end $$;
do $$ begin create type table_status as enum ('available', 'occupied', 'cleaning', 'billing'); exception when duplicate_object then null; end $$;
do $$ begin create type dining_session_status as enum ('open', 'closed'); exception when duplicate_object then null; end $$;
do $$ begin create type payment_status as enum ('unpaid', 'paid'); exception when duplicate_object then null; end $$;
do $$ begin create type payment_method as enum ('cash'); exception when duplicate_object then null; end $$;
do $$ begin create type order_status as enum ('open', 'completed', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type order_item_status as enum ('pending', 'cooking', 'ready', 'out_for_serving', 'served', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type priority_level as enum ('normal', 'rush'); exception when duplicate_object then null; end $$;
do $$ begin create type transaction_type as enum ('usage', 'manual_adjustment'); exception when duplicate_object then null; end $$;

create table if not exists app_users (
  user_id uuid primary key default gen_random_uuid(),
  full_name text not null,
  username text not null unique,
  password_hash text not null,
  role app_role not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

comment on table app_users is 'Staff login rows for cashier, kitchen, waiter, and manager roles. deleted_at is used for soft delete.';

create table if not exists restaurant_tables (
  table_code varchar(2) primary key,
  capacity integer not null default 4 check (capacity = 4),
  status table_status not null default 'available',
  cleaning_started_at timestamptz
);

comment on table restaurant_tables is 'Fifteen physical tables. table_code such as 01 or 15 is the identifier used by the UI.';

create table if not exists menu_categories (
  category_id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists inventory_items (
  ingredient_id bigint generated by default as identity primary key,
  name text not null,
  unit text not null,
  quantity_on_hand numeric(12,2) not null default 0 check (quantity_on_hand >= 0),
  reorder_level numeric(12,2) not null default 0 check (reorder_level >= 0),
  unit_cost numeric(12,4) not null default 0 check (unit_cost >= 0),
  deleted_at timestamptz
);

comment on table inventory_items is 'Ingredient stock master. deleted_at soft-hides ingredients while keeping history.';
comment on column inventory_items.reorder_level is 'Low-stock threshold used by the inventory and manager dashboard.';
comment on column inventory_items.unit_cost is 'Average ingredient cost per unit, used for dashboard cost calculations.';

create table if not exists menu_items (
  menu_id bigint generated by default as identity primary key,
  category_id bigint not null references menu_categories(category_id),
  name text not null,
  description text not null default '',
  image_url text not null default '',
  is_available boolean not null default true,
  deleted_at timestamptz
);

comment on table menu_items is 'Customer-facing buffet menu. Individual selling price is omitted because this is an all-you-can-eat model.';

create table if not exists recipes (
  menu_id bigint not null references menu_items(menu_id) on delete cascade,
  ingredient_id bigint not null references inventory_items(ingredient_id),
  quantity_used numeric(12,2) not null check (quantity_used > 0),
  primary key (menu_id, ingredient_id)
);

comment on table recipes is 'Recipe bridge table. One menu item can consume many ingredients and one ingredient can be used by many menu items.';

create table if not exists dining_sessions (
  session_id uuid primary key default gen_random_uuid(),
  table_code varchar(2) not null references restaurant_tables(table_code),
  cashier_id uuid references app_users(user_id),
  adult_count integer not null default 0 check (adult_count >= 0),
  child_count integer not null default 0 check (child_count >= 0),
  adult_price_snapshot numeric(10,2) not null default 399 check (adult_price_snapshot >= 0),
  child_price_snapshot numeric(10,2) not null default 259 check (child_price_snapshot >= 0),
  opened_at timestamptz not null default now(),
  bill_requested_at timestamptz,
  closed_at timestamptz,
  status dining_session_status not null default 'open',
  payment_status payment_status not null default 'unpaid',
  check (adult_count + child_count <= 4)
);

comment on table dining_sessions is 'One customer visit at one table. Price columns are snapshots so historical bills stay correct after price changes.';

create unique index if not exists uq_open_session_per_table
  on dining_sessions(table_code)
  where status = 'open';

create table if not exists orders (
  order_id bigint generated by default as identity primary key,
  session_id uuid not null references dining_sessions(session_id) on delete cascade,
  ordered_at timestamptz not null default now(),
  status order_status not null default 'open'
);

comment on table orders is 'Order header created each time the customer presses SEND ORDER.';

create table if not exists order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references orders(order_id) on delete cascade,
  menu_id bigint not null references menu_items(menu_id),
  quantity integer not null check (quantity > 0),
  status order_item_status not null default 'pending',
  special_instructions text not null default '',
  priority_level priority_level not null default 'normal',
  expedited_at timestamptz,
  requested_at timestamptz not null default now(),
  cooking_at timestamptz,
  ready_at timestamptz,
  out_for_serving_at timestamptz,
  served_at timestamptz,
  cancelled_at timestamptz
);

comment on table order_items is 'Line items sent to kitchen and waiter screens. requested_at starts the shared kitchen/waiter timer.';

create table if not exists payments (
  payment_id bigint generated by default as identity primary key,
  session_id uuid not null references dining_sessions(session_id),
  cashier_id uuid references app_users(user_id),
  method payment_method not null default 'cash',
  paid_amount numeric(10,2) not null check (paid_amount >= 0),
  paid_at timestamptz not null default now(),
  status payment_status not null default 'paid'
);

create table if not exists staff_activity_logs (
  activity_id bigint generated by default as identity primary key,
  user_id uuid references app_users(user_id),
  action text not null,
  entity_type text not null,
  entity_id text not null,
  occurred_at timestamptz not null default now()
);

comment on table staff_activity_logs is 'Simple staff audit trail for insert, update, soft delete, login, and workflow actions.';

create table if not exists inventory_transactions (
  transaction_id bigint generated by default as identity primary key,
  ingredient_id bigint not null references inventory_items(ingredient_id),
  order_item_id bigint references order_items(order_item_id),
  transaction_type transaction_type not null,
  quantity_change numeric(12,2) not null,
  unit_cost_snapshot numeric(12,4) not null default 0,
  occurred_at timestamptz not null default now()
);

comment on table inventory_transactions is 'Stock ledger. usage rows are automatic from served food; manual_adjustment rows come from manager inventory edits.';

create index if not exists idx_dining_sessions_table_status on dining_sessions(table_code, status, opened_at desc);
create index if not exists idx_orders_session_time on orders(session_id, ordered_at desc);
create index if not exists idx_order_items_status_time on order_items(status, requested_at);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_payments_paid_at on payments(paid_at desc);
create index if not exists idx_activity_time on staff_activity_logs(occurred_at desc);
create index if not exists idx_inventory_transactions_time on inventory_transactions(occurred_at desc, transaction_type);
create index if not exists idx_inventory_items_active_stock on inventory_items(deleted_at, quantity_on_hand);
create index if not exists idx_menu_items_active_category on menu_items(category_id) where deleted_at is null and is_available = true;

create or replace function request_bill(p_session_id uuid, p_cashier_user_id uuid)
returns void
language plpgsql
as $$
declare
  v_table_code varchar(2);
begin
  select table_code into v_table_code from dining_sessions where session_id = p_session_id and status = 'open';
  if v_table_code is null then
    raise exception 'Open dining session not found';
  end if;

  update dining_sessions set bill_requested_at = now() where session_id = p_session_id;
  update restaurant_tables set status = 'billing', cleaning_started_at = null where table_code = v_table_code;

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_cashier_user_id, 'request_bill', 'dining_session', p_session_id::text);
end;
$$;

create or replace function process_cash_payment(p_session_id uuid, p_cashier_user_id uuid)
returns numeric
language plpgsql
as $$
declare
  v_session dining_sessions%rowtype;
  v_total numeric(10,2);
begin
  select * into v_session from dining_sessions where session_id = p_session_id and status = 'open';
  if not found then
    raise exception 'Open dining session not found';
  end if;

  v_total :=
    v_session.adult_count * v_session.adult_price_snapshot +
    v_session.child_count * v_session.child_price_snapshot;

  update order_items
  set status = 'cancelled', cancelled_at = coalesce(cancelled_at, now())
  where order_id in (select order_id from orders where session_id = p_session_id)
    and status in ('pending', 'cooking', 'ready', 'out_for_serving');

  insert into payments (session_id, cashier_id, method, paid_amount, paid_at, status)
  values (p_session_id, p_cashier_user_id, 'cash', v_total, now(), 'paid');

  update dining_sessions
  set status = 'closed', payment_status = 'paid', closed_at = now()
  where session_id = p_session_id;

  update restaurant_tables
  set status = 'cleaning', cleaning_started_at = now()
  where table_code = v_session.table_code;

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_cashier_user_id, 'checkout_paid', 'dining_session', p_session_id::text);

  return v_total;
end;
$$;

create or replace function release_completed_cleaning_tables()
returns integer
language plpgsql
as $$
declare
  v_count integer;
begin
  update restaurant_tables
  set status = 'available', cleaning_started_at = null
  where status = 'cleaning'
    and cleaning_started_at <= now() - interval '10 minutes';

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function start_preparing_order_item(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'cooking', cooking_at = coalesce(cooking_at, now())
  where order_item_id = p_order_item_id and status = 'pending';

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'start_preparing', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function mark_order_item_ready(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'ready', ready_at = coalesce(ready_at, now())
  where order_item_id = p_order_item_id and status in ('pending', 'cooking');

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'mark_ready', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function expedite_order_item(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'ready',
      priority_level = 'rush',
      expedited_at = coalesce(expedited_at, now()),
      ready_at = coalesce(ready_at, now())
  where order_item_id = p_order_item_id
    and status in ('pending', 'cooking', 'ready');

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'expedite_order', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function send_order_item_to_table(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
begin
  update order_items
  set status = 'out_for_serving', out_for_serving_at = coalesce(out_for_serving_at, now())
  where order_item_id = p_order_item_id and status = 'ready';

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'send_to_table', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function serve_order_item(p_order_item_id bigint, p_actor_user_id uuid)
returns void
language plpgsql
as $$
declare
  v_item order_items%rowtype;
  v_recipe record;
begin
  select * into v_item from order_items where order_item_id = p_order_item_id;
  if not found or v_item.status not in ('ready', 'out_for_serving') then
    raise exception 'Only ready or out-for-serving items can be served';
  end if;

  if exists (
    select 1
    from recipes r
    join inventory_items i on i.ingredient_id = r.ingredient_id
    where r.menu_id = v_item.menu_id
      and i.deleted_at is null
      and i.quantity_on_hand < r.quantity_used * v_item.quantity
  ) then
    raise exception 'Ingredient stock is too low to serve this item';
  end if;

  for v_recipe in
    select r.ingredient_id, r.quantity_used, i.unit_cost
    from recipes r
    join inventory_items i on i.ingredient_id = r.ingredient_id
    where r.menu_id = v_item.menu_id
  loop
    update inventory_items
    set quantity_on_hand = quantity_on_hand - (v_recipe.quantity_used * v_item.quantity)
    where ingredient_id = v_recipe.ingredient_id;

    insert into inventory_transactions (
      ingredient_id,
      order_item_id,
      transaction_type,
      quantity_change,
      unit_cost_snapshot,
      occurred_at
    )
    values (
      v_recipe.ingredient_id,
      p_order_item_id,
      'usage',
      -(v_recipe.quantity_used * v_item.quantity),
      v_recipe.unit_cost,
      now()
    );
  end loop;

  update order_items
  set status = 'served',
      out_for_serving_at = coalesce(out_for_serving_at, now()),
      served_at = coalesce(served_at, now())
  where order_item_id = p_order_item_id;

  update orders
  set status = 'completed'
  where order_id = v_item.order_id
    and not exists (
      select 1 from order_items
      where order_id = v_item.order_id
        and status not in ('served', 'cancelled')
    );

  insert into staff_activity_logs (user_id, action, entity_type, entity_id)
  values (p_actor_user_id, 'serve_item', 'order_item', p_order_item_id::text);
end;
$$;

create or replace function delete_all_yum_yum_buffet_data()
returns void
language plpgsql
as $$
begin
  truncate table
    inventory_transactions,
    staff_activity_logs,
    payments,
    order_items,
    orders,
    dining_sessions,
    recipes,
    menu_items,
    inventory_items,
    menu_categories,
    restaurant_tables,
    app_users
  restart identity cascade;
end;
$$;

alter table app_users disable row level security;
alter table restaurant_tables disable row level security;
alter table menu_categories disable row level security;
alter table inventory_items disable row level security;
alter table menu_items disable row level security;
alter table recipes disable row level security;
alter table dining_sessions disable row level security;
alter table orders disable row level security;
alter table order_items disable row level security;
alter table payments disable row level security;
alter table staff_activity_logs disable row level security;
alter table inventory_transactions disable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select, update on all sequences in schema public to anon, authenticated;
